In [28]:
from tensorflow.keras.preprocessing.text import one_hot

In [29]:
##Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [30]:
##Define the vocabulary size
voc_size = 10000

In [31]:
##One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr


[[8764, 7824, 2025, 4846],
 [8764, 7824, 2025, 583],
 [8764, 5086, 2025, 237],
 [5943, 475, 2944, 2680, 2870],
 [5943, 475, 2944, 2680, 3991],
 [6985, 8764, 4641, 2025, 9491],
 [1014, 8471, 5224, 2680]]

In [32]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [33]:
import numpy as np

In [34]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8764 7824 2025 4846]
 [   0    0    0    0 8764 7824 2025  583]
 [   0    0    0    0 8764 5086 2025  237]
 [   0    0    0 5943  475 2944 2680 2870]
 [   0    0    0 5943  475 2944 2680 3991]
 [   0    0    0 6985 8764 4641 2025 9491]
 [   0    0    0    0 1014 8471 5224 2680]]


In [35]:
##Feature Representation
dim = 10


In [36]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [37]:
model.build(input_shape=(None, sent_length))
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
# Create dummy input data (batch size of 1)
import numpy as np
sample_input = np.array(embedded_docs[:1])  # Use part of your padded data as input

# Run the model on the sample input
model.predict(sample_input)

# Now check the summary again
model.summary()


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 ,
         -0.01664783, -0.004615  ,  0.00901164,  0.04972783,
          0.0413538 ,  0.00335056],
        [ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 ,
         -0.01664783, -0.004615  ,  0.00901164,  0.04972783,
          0.0413538 ,  0.00335056],
        [ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 ,
         -0.01664783, -0.004615  ,  0.00901164,  0.04972783,
          0.0413538 ,  0.00335056],
        [ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 ,
         -0.01664783, -0.004615  ,  0.00901164,  0.04972783,
          0.0413538 ,  0.00335056],
        [ 0.03111405, -0.01793978, -0.02621311,  0.02322394,
         -0.04406983,  0.03307744, -0.01206652,  0.04066927,
          0.04265973, -0.00466778],
        [-0.03461339, -0.03203009,  0.00548317, -0.01339629,
         -0.0315574 ,  0.04609379, -0.02907416, -0.04225062,
         -0.03866761,  0.0295676 ],
        [ 0.03306163, -0.04519486,  0.02354546, -0.0

In [40]:
embedded_docs[0]

array([   0,    0,    0,    0, 8764, 7824, 2025, 4846])

In [41]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step


array([[ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 , -0.01664783,
        -0.004615  ,  0.00901164,  0.04972783,  0.0413538 ,  0.00335056],
       [ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 , -0.01664783,
        -0.004615  ,  0.00901164,  0.04972783,  0.0413538 ,  0.00335056],
       [ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 , -0.01664783,
        -0.004615  ,  0.00901164,  0.04972783,  0.0413538 ,  0.00335056],
       [ 0.0470002 , -0.00935582,  0.04299415, -0.0082633 , -0.01664783,
        -0.004615  ,  0.00901164,  0.04972783,  0.0413538 ,  0.00335056],
       [ 0.03111405, -0.01793978, -0.02621311,  0.02322394, -0.04406983,
         0.03307744, -0.01206652,  0.04066927,  0.04265973, -0.00466778],
       [-0.03461339, -0.03203009,  0.00548317, -0.01339629, -0.0315574 ,
         0.04609379, -0.02907416, -0.04225062, -0.03866761,  0.0295676 ],
       [ 0.03306163, -0.04519486,  0.02354546, -0.01846832, -0.04786303,
         0.005055  , -0.03775669, -0.00702266